name: Push-to-azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Azure VM and mark Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Start GitHub Deployment (marks it as "production")
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.ref }}

      - name: Deploy files to Azure VM via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.Azure_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          ARGS: "-avz --delete"
          EXCLUDE: ".git/, .github/, .gitignore, README.md"

      - name: Ensure Apache is running and sync to /var/www/html
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.Azure_SSH_KEY }}
          script: |
            if [ ! -f /var/www/html/.apache_installed ]; then
              sudo apt-get -y update
              sudo apt-get install -y apache2
              sudo systemctl start apache2
              sudo systemctl enable apache2
              sudo touch /var/www/html/.apache_installed
            fi

            # Sync from TARGET_DIR to /var/www/html if needed
            if [ "${{ secrets.TARGET_DIR }}" != "/var/www/html" ]; then
              sudo rsync -av ${{ secrets.TARGET_DIR }}/ /var/www/html/
            fi

      # Mark deployment as successful
      - name: Mark GitHub Deployment as Successful
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
